In [1]:
from random import *
import numpy as np
import random


In [2]:
rounds = 5.0
price = float(input("Enter the price of the overall game."))
number_players = float(input("Enter the number of players you want to play the game (Ideal value 3->4)"))

Enter the price of the overall game.10000
Enter the number of players you want to play the game (Ideal value 3->4)4


In [3]:
mean_price = float(price) / float(rounds)
dev = 0.01 * float(mean_price) * float(randrange(1,15))
inherant_chars = [0] * int(number_players)
i = 0
c = 0
c_array = [10] * int(number_players)
for i in range(int(number_players)):
    c = int(randrange(0, int(number_players)))
    while(c in c_array):
        c = int(randrange(0, int(number_players)))
    c_array[i] = c
    inherant_chars[c] = mean_price - ((((number_players) - (number_players/2) + i) * dev))
inherant_chars

[1680.0, 1600.0, 1760.0, 1840.0]

In [7]:
card_influence = [0] * 10
i = 0

for i in range(0, 10):
    card_influence[i] = (0.2 * (i + 1))
card_influence

[0.2,
 0.4,
 0.6000000000000001,
 0.8,
 1.0,
 1.2000000000000002,
 1.4000000000000001,
 1.6,
 1.8,
 2.0]

In [8]:
rounds_won = [0] * int(rounds)
r = 0
for r in range(int(rounds)):
    #Assigning the players a card w/o replacement each from 1 - 10
    card_received = np.zeros(int(number_players))
    i = 0
    for i in range(int(number_players)):
        card = int(randrange(1, 11))
        while(card in card_received):
            card = int(randrange(1, 11))
        card_received[i] = card
    card_received  
    #giving the bid some value based on the card
    card_dependence = np.zeros(int(number_players))
    i = 0
    for i in range(int(number_players)):
        card_dependence[i] = card_influence[int(card_received[i]) - 1]
    bid = np.zeros(int(number_players))
    
    print(card_dependence)
    i = 0
    for i in range(int(number_players)):
        bid[i] = inherant_chars[i]*card_dependence[i]
    bid_winner = np.argmax((bid))
    print(f"The bids of the round {r+1} are -")
    print(bid)
    #bid_winner
    print(f"The bid of round {r + 1} was won by player number {bid_winner + 1}")
    print(card_received[bid_winner])
    print(card_received)
    card_received[bid_winner] = card_received[bid_winner] + int(randrange(11,14))
    #card_received[bid_winner]
    
    i = 0
    for i in range(int(number_players)):
        if(i == bid_winner):
            continue
        card = int(randrange(1, 11))
        while(card in card_received):
            card = int(randrange(1, 11))
        card_received[i] = card_received[i] + card
    #card_received  
    round_winner = np.argmax(card_received)
    print(card_received)
    print(f"The round {r + 1} was won by player number {round_winner + 1}")
    rounds_won[r] = round_winner + 1
    
    

[0.8 1.8 0.6 1.2]
The bids of the round 1 are -
[1344. 2880. 1056. 2208.]
The bid of round 1 was won by player number 2
9.0
[4. 9. 3. 6.]
[ 6. 20.  8. 13.]
The round 1 was won by player number 2
[1.8 1.6 1.  2. ]
The bids of the round 2 are -
[3024. 2560. 1760. 3680.]
The bid of round 2 was won by player number 4
10.0
[ 9.  8.  5. 10.]
[12. 18. 14. 21.]
The round 2 was won by player number 4
[1.4 0.8 1.2 0.2]
The bids of the round 3 are -
[2352. 1280. 2112.  368.]
The bid of round 3 was won by player number 1
7.0
[7. 4. 6. 1.]
[20. 12.  9.  9.]
The round 3 was won by player number 1
[1.4 1.8 2.  1.2]
The bids of the round 4 are -
[2352. 2880. 3520. 2208.]
The bid of round 4 was won by player number 3
10.0
[ 7.  9. 10.  6.]
[11. 16. 22. 13.]
The round 4 was won by player number 3
[0.6 0.2 0.8 0.4]
The bids of the round 5 are -
[1008.  320. 1408.  736.]
The bid of round 5 was won by player number 3
4.0
[3. 1. 4. 2.]
[ 7.  4. 16. 12.]
The round 5 was won by player number 3


In [6]:
overall_winner = np.bincount(rounds_won).argmax()
print(f"The overall winner of the game is player number {overall_winner}")

The overall winner of the game is player number 1


# 