In [1]:
from random import *
import numpy as np
import random


In [2]:
rounds = 5.0
price = float(input("Enter the price of the overall game."))
number_players = float(input("Enter the number of players you want to play the game (Ideal value 3->4)"))

Enter the price of the overall game.10000
Enter the number of players you want to play the game (Ideal value 3->4)4


In [11]:
mean_price = float(price) / float(number_players * rounds)
dev = 0.01 * float(mean_price) * float(randrange(1,15))
inherant_chars = [0] * int(number_players)
i = 0
c = 0
c_array = [10] * int(number_players)
for i in range(int(number_players)):
    c = int(randrange(0, int(number_players)))
    while(c in c_array):
        c = int(randrange(0, int(number_players)))
    c_array[i] = c
    inherant_chars[c] = mean_price - ((((number_players) - (number_players/2) + i) * dev))
inherant_chars

[360.0, 290.0, 150.0, 220.0]

In [12]:
card_influence = [0] * 10
i = 0
for i in range(0, 10):
    card_influence[i] = 0.2 * (i + 1)
card_influence

[0.2,
 0.4,
 0.6000000000000001,
 0.8,
 1.0,
 1.2000000000000002,
 1.4000000000000001,
 1.6,
 1.8,
 2.0]

In [13]:
rounds_won = [0] * int(rounds)
r = 0
for r in range(int(rounds)):
    #Assigning the players a card w/o replacement each from 1 - 10
    card_received = np.zeros(int(number_players))
    i = 0
    for i in range(int(number_players)):
        card = int(randrange(1, 11))
        while(card in card_received):
            card = int(randrange(1, 11))
        card_received[i] = card
    card_received  
    #giving the bid some value based on the card
    card_dependence = np.zeros(int(number_players))
    i = 0
    for i in range(int(number_players)):
        card_dependence[i] = card_influence[int(card_received[i]) - 1]
    bid = np.zeros(int(number_players))
    i = 0
    for i in range(int(number_players)):
        bid[i] = inherant_chars[i] * card_dependence[i]
    bid_winner = np.argmax((bid))
    print(f"The bids of the round {r+1} are -")
    print(bid)
    #bid_winner
    print(f"The bid of round {r + 1} was won by player number {bid_winner + 1}")
    print(card_received[bid_winner])
    print(card_received)
    card_received[bid_winner] = card_received[bid_winner] + int(randrange(11,15))
    #card_received[bid_winner]
    
    i = 0
    for i in range(int(number_players)):
        if(i == bid_winner):
            continue
        card = int(randrange(1, 11))
        while(card in card_received):
            card = int(randrange(1, 11))
        card_received[i] = card_received[i] + card
    #card_received  
    round_winner = np.argmax(card_received)
    print(card_received)
    print(f"The round {r + 1} was won by player number {round_winner + 1}")
    rounds_won[r] = round_winner + 1
    
    

The bids of the round 1 are -
[432. 116. 240. 132.]
The bid of round 1 was won by player number 1
6.0
[6. 2. 8. 3.]
[17.  3. 14. 12.]
The round 1 was won by player number 1
The bids of the round 2 are -
[216. 348. 150. 308.]
The bid of round 2 was won by player number 2
6.0
[3. 6. 5. 7.]
[12. 18. 15. 10.]
The round 2 was won by player number 2
The bids of the round 3 are -
[144. 406. 300.  44.]
The bid of round 3 was won by player number 2
7.0
[ 2.  7. 10.  1.]
[ 6. 21. 15.  9.]
The round 3 was won by player number 2
The bids of the round 4 are -
[288. 406.  30. 264.]
The bid of round 4 was won by player number 2
7.0
[4. 7. 1. 6.]
[ 9. 21.  6.  7.]
The round 4 was won by player number 2
The bids of the round 5 are -
[ 72. 116. 210. 132.]
The bid of round 5 was won by player number 3
7.0
[1. 2. 7. 3.]
[10.  6. 19.  4.]
The round 5 was won by player number 3


In [14]:
overall_winner = np.bincount(rounds_won).argmax()
print(f"The overall winner of the game is player number {overall_winner}")

The overall winner of the game is player number 2
